name: cgddnet
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-learn
  - pillow
  - pyyaml
  - tqdm
  - pip
  - pip:
      - opencv-python-headless
      - fvcore
      - pytest
